- src/Checklists/Checklist/Progress.tsx
- src/Checklists/Checklist/__tests__/Progress.test.tsx
- src/Checklists/HeroChecklist/HeroChecklist.tsx
- src/Checklists/ModalChecklist/ModalChecklist.tsx
- src/Checklists/ProgressBadge/__tests__/ProgressBadge.test.tsx
- src/Checklists/ProgressBadge/index.tsx
- src/Checklists/ProgressBadge/styled.ts
- src/FrigadeProgressBadge/index.tsx
- src/components/Icons/Chevron.tsx
- src/index.ts
- Loads progress for given flow
Example usage:
```
<FrigadeProgressBadge
flowId='flow_xyz'
title="Get Started"
style={{ backgroundColor: '#3661E1', borderColor: '#3661E1'}}
primaryColor="#FFFFFF"
secondaryColor="rgba(255, 255, 255, 0.4)"
textStyle={{ color: '#FFFFFF'}}
onClick={() => console.log('clicked item...')}
/>
```
Props
- `primaryColor`: text, chevron, and progress bar fill colors
- `secondaryColor`: progress bar bg
- `title` could probably be set from the Flow, but just being passed in as own prop at the moment
> Progress badge

- src/FrigadeGuide/FrigadeGuide.tsx
- src/FrigadeGuide/index.tsx
- src/Guides/Guide.tsx
- src/Guides/__tests__/Guide.test.tsx
- src/Guides/index.tsx
- src/Guides/styled.ts
- src/index.ts
- Pulling the "guide" portion of the ChecklistWithGuide out into its own component
- Currently doesn't have state, and includes a new "icon" field 
- Todo: should allow icon to be an image src/uri
| Example: https://app.frigade.com/flows/flow_Vk7HdLxGsseJKlaX |
| --- |
| <img width="1488" alt="Screen Shot 2023-02-25 at 12 15 57 PM" src="https://user-images.githubusercontent.com/11068205/221376091-cb2a0395-043c-4130-9ee5-24c7403d30c2.png"> |
> feat: guide component

- src/Checklists/ChecklistWithGuide/ChecklistWithGuide.tsx
- src/Checklists/ChecklistWithGuide/__tests__/ChecklistWithGuide.test.tsx
- src/Checklists/ChecklistWithGuide/index.tsx
- src/Checklists/ChecklistWithGuide/styled.ts
- src/Checklists/ModalChecklist/ModalChecklist.tsx
- src/FrigadeChecklist/index.tsx
- src/Guides/Guide.tsx
- src/Guides/styled.ts
> feat: checklist with guide appearance handling

- src/Checklists/ChecklistWithGuide/ChecklistWithGuide.tsx
- src/FrigadeChecklist/index.tsx
- src/api/completionUtil.ts
- src/api/flows.ts
- src/components/CheckBox/index.tsx
- src/types/index.tsx
- If step contains a `user.flow('flow-id').state == 'COMPLETED_FLOW'` completion criteria, fetch the current progress of the flow and pass down as `progress` prop to the step + checkbox
https://user-images.githubusercontent.com/11068205/222913365-8cf129f6-632a-4ac0-bfa1-654f947f67b0.mov
> feat: step flow progress for flow completion criteria

- src/types/index.tsx
- The `mergeAppearanceWithDefault` function was returning objects shallow copied form the `DefaultAppearance`. This means that if we set `theme.primaryColor` for one component, it will also be set for other components in use
- e.g. setting the `theme.colorPrimary: '#ffffff'` for the `FrigadeProgressBadge` was causing the modal checklist to also try and render itself with a `theme.colorPrimary: '#ffffff'` instead of whatever color was passed to it
- used the object -> string -> object method suggested here: https://developer.mozilla.org/en-US/docs/Glossary/Deep_copy
> feat: use deep copy for default appearance

- src/Checklists/ModalChecklist/CollapsibleStep/index.tsx
- src/Checklists/ModalChecklist/CollapsibleStep/styled.ts
- src/Checklists/ModalChecklist/ModalChecklist.tsx
- src/Checklists/ModalChecklist/styled.ts
- src/components/Modal/index.tsx
- src/types/index.tsx
- Pass appearance down through modal checklist
- Adds `colorBorder` field to `BaseTheme` type
| Default | Dark |
| --- | --- |
| <img width="718" alt="Screen Shot 2023-03-08 at 10 31 26 AM" src="https://user-images.githubusercontent.com/11068205/223787185-85123416-c4ed-4725-b085-a987b1ff447b.png"> | <img width="739" alt="Screen Shot 2023-03-08 at 10 31 16 AM" src="https://user-images.githubusercontent.com/11068205/223787190-e182105e-252a-4d7a-b042-c56cd4528c5c.png"> |
> fix: add appearance handling for modal checklist

- src/Checklists/ChecklistWithGuide/ChecklistWithGuide.tsx
- src/Checklists/HeroChecklist/HeroChecklist.tsx
- src/Checklists/HeroChecklist/StepChecklistItem.tsx
- src/Checklists/ModalChecklist/ModalChecklist.tsx
- src/FrigadeBanner/index.tsx
- src/FrigadeChecklist/index.tsx
- src/FrigadeForm/FormContent.tsx
- src/FrigadeForm/FormFooter.tsx
- src/FrigadeForm/index.tsx
- src/FrigadeGuide/FrigadeGuide.tsx
- src/FrigadeTour/index.tsx
- src/Guides/Guide.tsx
- src/Tooltips/Tooltips.tsx
- src/Tooltips/index.tsx
- src/api/flows.ts
- src/components/Modal/index.tsx
- src/components/Progress/ProgressRing/ProgressRing.tsx
- src/types/index.tsx
In the grand tradition of yak shaving:
1. I'm finishing up the standalone wrapper for the sdk
2. ...and I want to `npm-link` and include the sdk into another local package for testing
3. ...and in order to do that, I need to run `yarn build` locally
4. ...and in order for the build to succeed, I need all existing TypeScript errors resolved.
Caveat: I'm still familiarizing myself with much of this code and I don't _think_ this will have broken anything, since any breakage should show up in the form of red underlines from the TypeScript compiler.
If there's a test instance with every component spun up in it where I can visually check everything lmk. If not, this might be the point where Storybook gets thrown in the SDK backlog 👀
> Fixed a whole mess of minor TSC issues

- src/api/flow-responses.ts
- src/api/organizations.tsx
- src/api/users.tsx
If I'm using strict eslint rules for hooks, then I need to add `addPropertiesToUser` to deps.
But once you call `addPropertiesToUser()`, then hook `useFrigadeUser` will initiate render and there will be a new function `addPropertiesToUser` created, that will call `useEffect` again and it will be an infinite loop.
```js
const { addPropertiesToUser } = useFrigadeUser()
useEffect(() => {
addPropertiesToUser({ firstName: user.firstName })
}, [user, addPropertiesToUser])
```
So, I memoized such functions with `useCallback`.
> fix: memoize functions to prevent useless rerenders

- src/FrigadeProvider/index.tsx
Simple example:
```jsx
function Wrapper({ user }: { user?: IUser | null }) {
return (
<FrigadeProvider
publicApiKey={process.env.REACT_APP_FRIGADE_PUBLIC_API_KEY ?? ''}
userId={user?.id}
organizationId={user?.organizationId}
>
<App />
</FrigadeProvider>
);
}
```
There might be cases when there is no `userId` or `organizationId` on first render, but it will be later.
So, it is better to update state/context after props change.
> fix: update context on props change

- package.json
- src/FrigadeProvider/index.tsx
- src/api/common.ts
- src/api/flow-responses.ts
- src/api/flows.ts
- src/api/organizations.tsx
- src/api/user-flow-states.ts
- src/api/users.tsx
- yarn.lock
Adds a error boundary where we try to achieve the following:
- In the case of any API failures to Frigade, we simply hide Frigade from the session.
- Errors still get logged in the console but don't catch on to any other error boundaries.
> Better Graceful degradation

- .babelrc.json
- package.json
- src/FrigadeForm/FormContent.tsx
- src/FrigadeForm/FormPagination.tsx
- src/FrigadeForm/__stories__/FrigadeForm.stories.tsx
- src/FrigadeForm/index.tsx
- yarn.lock
**Changelog:**
- Added pagination for multi-step announcements
- Refactored FormContent a bit to tidy up how it wraps itself in animations for `large-modal`
- Added a basic shell to Storybook for testing Announcements.
- Added a babel config for Storybook v7 (they dropped default configs in this version, so we have to provide our own)
> FRI-385 Multi-step announcement w/ pagination

- src/api/flows.ts
Currently `flowId` is used as the name of the parameter in all other functions while `getFlow` uses slug. Migrating the name so end user understands its the same value.
> fix: change slug => flowId to match other exposed function signatures

- packages/react/src/components/Tooltip/index.tsx
Tested the tour in Storybook to ensure it worked as expected (text/buttons work, spotlight on/off works)
> fix: tour freezing entire page until dismissed

- packages/reactv1/src/components/CheckBox/index.tsx
- packages/reactv1/src/components/CheckBoxRow/index.tsx
- packages/reactv1/src/components/Checklists/HeroChecklist/HeroChecklist.tsx
- packages/reactv1/src/components/Checklists/HeroChecklist/StepChecklistItem.tsx
This PR is meant to address several a11y issues on the Hero Checklist module. These are:
- Checkboxes now correctly set aria-checked on divs with `role="checkbox"`, so the check state is correctly reported. The `aria-checked` value only sets to true if `{value}` is explicitly to true; otherwise, this is set to false to catch undefined, nulls, etc.
- The Hero Checklist now has a parent role of `list`, as each checklist item has a child role of `listitem`.
- Labels are now correctly passed to checkboxes to associate the text together. This solution is a little kludgey (pass the value of label to the child checkbox component), and ideally an ID-driven `aria-labelledby` solution would be created, but I didn't want to change too much of the project.
- I noticed a slight typo on the `layoutId` …
> a11y fixes on Hero Checklist module

- packages/react/src/components/Tooltip/index.tsx
Currently zIndex does not get passed to the Tooltip Spotlight resulting in scenarios where the Tooltip content is shown but the Spotlight is hidden.
> Tooltip spotlight add zIndex from props

- apps/smithy/src/stories/Collection/Collection.stories.tsx
- packages/js-api/src/core/flow.ts
- packages/react/src/components/Flow/FlowProps.ts
- packages/react/src/components/Flow/index.tsx
- Flow type now allows a `props` object at the top level, same as the existing `props` on FlowStep
- Flow Component now accepts a `modal` prop to manually flag a Flow embed as being modal
- Flow Component now automatically flags `FlowType.ANNOUNCEMENT` and `FlowType.TOUR` as modal
The main impetus for these changes was around enabling Collections, with a few minor QoL enhancements added in along the way.
> Modal fixes and top-level props

- packages/react/src/components/Tooltip/index.tsx
- packages/reactv1/src/components/Tooltips/Tooltips.tsx
Frigade Tour component's tooltip tries to anchor to `steps[index].selector` even if the DOM element has `display: none`.
This results in a tooltip rendered at the upper left corner of the screen.
If the anchor is invisible, treat it as if the anchor is missing.
> Fix issues with invisible tooltip anchors

- apps/smithy/src/stories/Collection/Collection.stories.tsx
- apps/smithy/src/stories/hooks/useFlow.stories.tsx
- packages/js-api/src/core/collections.ts
- packages/js-api/src/core/flow.ts
- packages/js-api/src/core/frigade.ts
- packages/js-api/test/rules.test.ts
- packages/react/src/components/Flow/index.tsx
- packages/react/src/hooks/useFlow.ts
- Rework `useFlow` to use `useSyncExternalStore`
- Temporarily disable orchestration between Collections (internal orchestration still enabled).
> Use flow update

- apps/smithy/src/stories/Announcement/Announcement.stories.tsx
- packages/react/src/components/Flow/index.tsx
- packages/react/src/components/Tour/index.tsx
- packages/react/src/hooks/useModal.ts
Fixes an issue where restarting a flow would prevent an announcement flow from opening up again due to colission detection.
https://github.com/user-attachments/assets/b3c1ca98-bc0d-474a-b097-c3246ddb5769
> fix: collission detection to respect flow.restart()

- apps/smithy/src/stories/Form/Form.stories.tsx
- packages/react/src/hooks/useModal.ts
This appears to fix the issue where a `<Form as={Dialog} />` doesn't spawn in some cases (it gets blocked by useModal because `flow` is undefined).
The real fix is to figure out why the hook doesn't run when `flow` becomes defined, but I wasn't able to figure this out just yet. This fix, however, does seem to work for all use cases in storybook (see attached demo).
https://github.com/user-attachments/assets/9bcfea53-c45d-4982-937e-730df605381d
> fix: as={Dialog} modal collision detection

- apps/smithy/src/stories/Collection/Collection.stories.tsx
- apps/smithy/src/stories/hooks/useFlow.stories.tsx
- packages/react/src/hooks/useModal.ts
As it turns out, the unmount function is not called in some cases when a route is changed. Therefore, we want to make sure we remove the current modal if the route changes. This fix also ensures that if the component reemerges on a different route, it will line up in the modal queue again.
> fix: remove modals on url change

- apps/smithy/src/stories/Announcement/Announcement.stories.tsx
- packages/js-api/src/core/frigade.ts
- packages/js-api/src/shared/fetchable.ts
- packages/js-api/src/shared/state.ts
- packages/js-api/src/shared/utils.ts
- packages/react/src/components/Provider/DefaultCollection.tsx
- packages/react/src/hooks/useCollection.ts
- packages/react/src/hooks/useCollections.ts
Cancels any pending requests if a URL change happens.
**Testing done**:
- Tested manually via storybook that modal flickers caused by non cancelling pending requests are correctly resolved (see demo).
- Tested existing storybook stories
https://github.com/user-attachments/assets/ea7c40fd-b63b-4b6f-a899-a992b855b80b
> fix: cancel pending requests on redirect

- apps/smithy/src/stories/Announcement/Announcement.stories.tsx
- apps/smithy/src/stories/Form/Form.stories.tsx
- packages/react/src/components/Announcement/index.tsx
- packages/react/src/components/Banner/index.tsx
- packages/react/src/components/Card/index.tsx
- packages/react/src/components/Checklist/Collapsible.tsx
- packages/react/src/components/Flow/index.tsx
- packages/react/src/components/Form/FormStep.tsx
- packages/react/src/components/Form/index.tsx
- Standardize how Flow-aware components handle prop overrides from YAML
- Same thing for the `dismissible` prop (except in Carousel, which for some reason doesn't have a dismiss button)
- Remove unneeded instances of the `<Flow as={null} ... >` pattern (I used it originally to get access to props from YAML, but those are now correctly merged and passed through to the top-level container that Flow renders)
Potential breaking change:
- Announcement no longer has an extraneous step wrapper. If CSS was targeted to it, that CSS will no longer apply.
> Flow props standardization

- apps/smithy/src/stories/Tour/Tour.stories.tsx
- apps/smithy/src/stories/Tour/TourInteractionTests.stories.tsx
- packages/react/src/components/Flow/FlowProps.ts
- packages/react/src/components/Flow/index.tsx
- packages/react/src/components/Hint/index.tsx
- packages/react/src/components/Hint/useFloatingHint.ts
- packages/react/src/components/Tour/Tour.tsx
- packages/react/src/components/Tour/TourStep.tsx
Ensures that we do not mark a tour started until the anchor shows up.
Testing done:
- Added a storybook story to ensure that we don't make a tour started until the anchor shows up 
- Tested existing tour/hint stories
- All tour integration tests pass
> feat: do not start a tour/hint flow until the anchor is visible

- .changeset/old-years-ring.md
- packages/js-api/src/core/frigade.ts
- packages/js-api/src/core/types.ts
- packages/js-api/src/shared/fetchable.ts
- packages/js-api/src/shared/utils.ts
Performance improvement that updates the behavior of `syncOnWindowUpdates` to debounce identical calls more aggressively. We set the default value to every 100ms but make it configurable via an internal prop.
Verified all existing storybook tests pass
> feat: debounce url change calls

- apps/smithy/src/stories/Collection/Collection.stories.tsx
- packages/js-api/src/core/collections.ts
- packages/js-api/src/core/flow.ts
- packages/react/src/hooks/useCollections.ts
Temporarily sets list of collection flows to empty while server-roundtrip for completed/dismissed/restarted flows continues. This is done in order to avoid the race condition where the frontend thinks it should render the next flow while in fact it should be in cool-off.
Testing done:
Reproduced the bug in the story "Multiple Announcements" and ensured it was fixed after applying the fix. Also tested existing collection integration tests.
> fix: remove optimistic writes from collections
